{% set name = "smartystreets_python_sdk" %}
{% set version = "4.11.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smartystreets_python_sdk-{{ version }}.tar.gz
  sha256: 92270a969d246e7ac5e538a6aa65307e374311b48e1886e05c9991e4a0d0e0bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5|>=2.7
  run:
    - python >=3.5|>=2.7
    - requests

test:
  imports:
    - smartystreets_python_sdk
    - smartystreets_python_sdk.international_street
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smartystreets/smartystreets-python-sdk
  summary: An official library to help Python developers easily access the SmartyStreets APIs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
